### ISSUE TITLE
Import songs from spotify playlists

### ISSUE THREAD

**Issue by Melvinfused** [25huizengek1/ViTune#172]
Could you add a feature to import spotify playlist? if there a way to import tracks from my spotify playlist.

**Comment by Enigma1309** [comment]
seems kinda out of scope..anyways let's see what @25huizengek1 has to say about it.

**Comment by 25huizengek1** [comment]
I guess it's out of scope for this project, indeed. You could probably just use an external Spotify playlist exporter tool, and import the resulting YouTube playlist in ViTune.

**Comment by Melvinfused** [comment]
How to import?

**Comment by Enigma1309** [comment]
save the playlist link to any app, say send it to whatsapp or signal self message and click the link,
if it show this then choose the open with ViMusic/ViTune button.
![image](https://github.com/25huizengek1/ViTune/assets/94917588/60295946-d8aa-4258-a01c-d862c3f662d9)

or else it will open the default app, say it opens in youtube..
then go to the specific app info page (yt in this case) and tap `clear open by defaults` option
![image](https://github.com/25huizengek1/ViTune/assets/94917588/b14feec0-f792-4cbb-a831-d4685d182c01)

I don't have yt that's why i'm showing Libretube, the steps are same for yt too..
and now click the link again.
it should popup an app picker, then choose ViMusic/ViTune from the app list.

---

Or You can host the same playlist to piped instance and login to access it from app

**Comment by 25huizengek1** [comment]
You don't have to share with yourself: you can just 'share' directly with ViTune.

**Comment by Melvinfused** [comment]
Still sharing spotify link to ViMusic does nothing but open ViMusic(ViTune) app, is there a way to import CSV?

**Comment by Melvinfused** [comment]
Wouldn't that be a good way to create ViMusic playlists from csv exports taken from other services??

**Comment by Enigma1309** [comment]
ViTune accepts yt links, to convert spotify playlist to yt playlist you have to use external app/website...
