### ISSUE TITLE
App Navigation Suggestions

### ISSUE THREAD

**Issue by archit9169** [25huizengek1/ViTune#183]
I wanted to list down some suggestions that can help with navigation in the app.

1. Merge quick picks and discover :- Only have a single home page where we can see contents of both the tabs. This will reduce the object count on the navigation bar.
2. Songs tab name is ambiguous :- This tab basically displays all the songs we have listened to, no matter if they were liked or not. It causes confusion sometimes when I want to see only liked songs. Please rename it to history or something else.
3. Create a Library tab :- This will have all liked songs, artist, albums along with the playlist tab stuff. This will again remove some objects from navigation tab, giving it minimalist look.

We can have more discussion on this if you need me to expand more on some points. Basically I would like this app to keep a minimalist look and easier navigation rather than a bunch of features that takes this in a completely new direction than ViMusic

**Comment by Enigma1309** [comment]
> Merge quick picks and discover

that is a pretty good discussion , also it would be better if the tiles provided by yt (like mood, song genres, languages,etc) are pre expanded by default in a list, this will create a kind of infinite scrolling for ex:-  
Screenshot from stremio (totally unrelated to music) 
![image](https://github.com/25huizengek1/ViTune/assets/94917588/8893de48-dc17-428b-b964-dd7cdd09e727)
in above screenshot we can have different genres of music since discover feature already provides that, we just need them to display in above manner..

> Songs tab name is ambiguous

according to me it's better this way, there's also a filter that would suit the song analogy rather than history, it's just an opinion btw let's see what others have to say

> Create a Library tab 

sounds good , let's see

**Comment by archit9169** [comment]
Yes, you might be right for the 2nd point. However I still feel it can be improved further somehow.

For eg, when clicking on playlist we get options for top 50, fav, offline. On clicking on of those options you get a new UI where the options get moved to the side navigation. Having something similar for the song tab can be an improvement.

So, when clicking song tab we get option like recents, queue, fav, offline, top 50 and have the playlist be seperated on a dedicated tab maybe under library where additional stuff like artist, album and local should be present.

The aim is to improve the UI through this discussion in such a way that there is less clutter, ease of understanding each tab, and at the same time keep the experience of ViMusic.

**Comment by genericbetatester** [comment]
I agree with your first suggestion, but I disagree with the other two because, the songs tab basically adds all the songs you have streamed which imo is a normal behavior for any music streaming app. But I think something that might be useful for you is "hide  unliked songs in library”. This means you have to like all the songs you want and it won't break the functionality of the tab.

Merging artist, album and playlist tab will only create confusion and add extra steps to access stuffs that are already easy to reach. Furthermore, opening an "artist" profile reveals a "library" tab which may create confusion.

**Comment by archit9169** [comment]
I tried other yt music clients, and on clicking songs tab on them it opens songs that are added to the library and not all the playback songs.

As it stands, when you click on artists tab it opens all liked artist. When you click albumbs tab it opens all liked albums, only songs tab behaviour is different.

Furthermore, your suggestion for "hide unliked songs in library", causes more confusion as the songs tab is not library. By saying library, it means that this is a place where you have to add things, while the current behaiour of songs tab reflects workings of recents/history page.

If you ooen settings and goto database, you can see that it says playback history. All these songs are being used to generate quick picks and top 50 charts are also being generated by using the contents of the songs tab. So ideally the names at both location should match.

I am not asking for the behaviour to be changed but rather to change the tab name so that it can reflect the actual usage of the tab rather than just an ambigous name as song.

**Comment by archit9169** [comment]
> Merging artist, album and playlist tab will only create confusion and add extra steps to access stuffs that are already easy to reach. Furthermore, opening an "artist" profile reveals a "library" tab which may create confusion.

I did not see the library tab oreviously, so you are correct with this point as this will only cause confusion.

How about this, lets have a seperate fav tab that has
a. Liked songs
b. Liked artist
c. Liked albums

And let the remaining tabs be as is. This will atleast reduce skme clutter on the navigation pane. Ideally I would like navigation pane to have at max 5 objects, not including the settings icon. Right now it has 7.

**Comment by Enigma1309** [comment]
> I am not asking for the behavior to be changed but rather to change the tab name so that it can reflect the actual usage of the tab rather than just an ambiguous name as song.

Could you give a better name idea ?
"History" wouldn't suit this much since that tab doesn't show history, it just shows the recently cached songs and new playback events, it doesn't show add old/cached song that are played recently.

---

> How about this, lets have a separate fav tab that has
a. Liked songs
b. Liked artist
c. Liked albums

This seems like a good idea, but wouldn't that cause increase of more tabs? 

> let the remaining tabs be as is.
 This will at-least reduce some clutter 

could you explain it ? am i getting something wrong ??

**Comment by archit9169** [comment]
Sure, something like the below.

1. Home :- Combined view of quick picks and discover
2. Recent Playback :- contents of the songs tab that generate quick picks anf top 50 charts
3. Favorites :- 
    a. Songs
    b. Albumbs
    c. Artists
4. Playlist :-
    a. Top 50
    b. Offline
    c. User created playlist
5. Local / Device

In this way, there is less clutter on the navigation pane, each category is better defined and represnet their main usage.

Also recent playback tab can be further improved in the future, I have more suggestion aboit that as well. However for now this discusiion is basically for naviagtion UI and not the actual feautres.

**Comment by Enigma1309** [comment]
> Recent Playback

the name can be improved further, since it's long (it will probably take more space..)


apart from that it looks all good :D

**Comment by archit9169** [comment]
> > Recent Playback
> 
> the name can be improved further, since it's long (it will probably take more space..)
> 
> apart from that it looks all good :D

At this point in time, this is all just discussion. Nothing is actually being changed or anything. So we can probably come up with far better solutions to this.

**Comment by SiddhantRakh** [comment]
Recently Played could simply be renamed to 'Recents'. I usually listen to things I've liked before be it songs, albums, or artists. Having to access my liked songs through the playlist view every time is a bit tedious. This would be a much-needed improvement.

**Comment by 25huizengek1** [comment]
Resolved by 08446d1f7d950056a810ccdda9ff8af6d80c55a8
