### ISSUE TITLE
Introduce Playlist Customization Options

### ISSUE THREAD

**Issue by creuserr** [25huizengek1/ViTune#207]
When I use ViMusic, it frustrates me that I can't customize my playlists.

Could you please add these customizations?

1. Playlist Image:
   - This would be the cover image of the playlist.

2. Playlist Description:
   - This would provide a description for the playlist. If you've ever come across an album, it typically displays its biography or description (often sourced from Wikipedia) below its image. I hope the same functionality can be applied to playlists.

**Comment by 25huizengek1** [comment]
What is the point? No, seriously, what does adding your own "description" add to the experience?

**Comment by creuserr** [comment]
it's just an additional customization... but my focus is on the thumbnail

**Comment by dtomvan** [comment]
Yeah, doesn't seem to be of any practical use to me. Besides, this would massively explode the size of our db.

**Comment by Shinichi-Here** [comment]
When we add a playlist with yt music link, does the app fetches Playlist Thumbnail ?

I have playlist with Latest AI Generated Thumbnails. Just curious of this as I haven't seen the thumbnail in ViTune.
(Asking this because if app is fetching the thumbnail, means this might be a bug)

And Thank you for the app. 
Between is there any social channel for these types of discussions on the app ?

**Comment by 25huizengek1** [comment]
@Shinichi-Here Thank you for your appreciation. I don't understand what you are suggesting, but you should either fill out a [feature request form](https://github.com/25huizengek1/ViTune/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) or [start a discussion about it](https://github.com/25huizengek1/ViTune/discussions/new?category=ideas), since this is not related to this issue.

**Comment by 25huizengek1** [comment]
I guess accounting for YouTube's custom playlist thumbnails should be enough for a good experience. I personally don't see the benefit of overcomplicating playlists even further by adding such customization features. This means that this issue can be closed, and we'll track the development of playlist thumbnails in #224
