### ISSUE TITLE
The new transition has a bug

### ISSUE THREAD

**Issue by FaqatZubair1** [25huizengek1/ViTune#232]
### Steps to reproduce the bug

Search for any song or artist
Try to go back
It doesn't wait for the back command to end
It also doesn't show any transition 

### Expected behavior

It should wait for me to lift my finger from the screen like it does the other times

### Actual behavior

It executes the back command without waiting for me to lift up my finger

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/161596117/3669f89e-b794-4932-a227-ae5873d16a75

### ViTune version

1.0.1 (12-04-2024)

### What kind of build are you using?

Nightly (F-Droid)

### Android version

Android 14

### Device info

Moto g34

### Upstream reproducibility

Not applicable.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
I was aware, so I didn't fully release it yet, thank you for the bug report though!

**Comment by dtomvan** [comment]
Hahah predictive back is difficult

**Comment by 25huizengek1** [comment]
As stated in the above commit, I opted to move predictive back to a feature branch for now, as the animation library that powers this animation (compose animation) seems way too unstable to actually use right now (some animations just straight up don't start), so I guess we can close this while I continue development, and I'll merge when the feature is actually ready. (and since it's only serving a cosmetical purpose, it doesn't have to have high priority)
