### ISSUE TITLE
Notifications for when new ViTune Update Available

### ISSUE THREAD

**Issue by CardMasterLive** [25huizengek1/ViTune#234]
Title kinda says it all

**Comment by 25huizengek1** [comment]
Good suggestion. This is definitely possible, but I don't want a centralized service that manages such notifications (FCM or something). This means that I'll have to implement it so that your devices checks for updates periodically (opt-in) and if there is an update, it should send a notification.

Is this what you want? I'm willing to add this, but only opt-in.

**Comment by CardMasterLive** [comment]
That was kinda the idea I was going for. An opt-in out-of-app periodic update check would be good as, at least from my experience as a more casual user that doesnt frequent GitHub too often, it would be easier to know when their are updates that could be beneficial from a security or functionality aspect
