### ISSUE TITLE
Compatible navigation with Android TV

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#238]
Since ViTune/ViMusic works pretty good on Android TV using Landscape, i was wondering if it could be compatible with navigation button system (DPAD). I tried something but its not very efficient.

![image](https://github.com/25huizengek1/ViTune/assets/1917871/6ca8064f-ee4f-4c1b-8f37-b02ae247c7a0)

**Comment by 25huizengek1** [comment]
Theoretically you can already use your D-Pad in order to navigate through ViTune, but since I had no intention for the best experience on TV, I deliberately chose to optimize the mobile experience. If I really want good Android TV support, I'd have to use Google's Android TV libraries in order to have full D-Pad support. I'm currently not planning to do this since actually releasing and maintaining a Android TV application outside of the Play Store is already a huge pain to deal with.

If you have suggestions to improve the current experience on TV, please let me know, and I'll see what I can do.

**Comment by dtomvan** [comment]
We won't support android tv. See: #219
