### ISSUE TITLE
Sharing a Song (Like Spotify, with the album cover)

### ISSUE THREAD

**Issue by JMPesce** [25huizengek1/ViTune#251]
I was wondering if there could be the potential to implement the ability to share a song to socials like you can in Spotify, where it shares the album art of the song and the title. Is this something that could potentially be implemented?

For example:

![tmp_EQZzoM_2d55b66555cda791_02](https://github.com/25huizengek1/ViTune/assets/6206297/b12c0580-6c8b-4d65-ace3-748e7cb4173e)

Something like this, to share to Instagram, Google Messages, etc., rather than sharing a Youtube Music link when we click "Share".

**Comment by 25huizengek1** [comment]
This already exists. Just click the three dots ('...') in the bottom-right corner of your screen, and click on the share icon right next to your song.

**Comment by JMPesce** [comment]
Sorry but that actually isn't the case. When you click on the three dots and click on the share button, it gives you a YouTube music link to share, which is not what I'm talking about:

![Screenshot_20240424-174051](https://github.com/25huizengek1/ViTune/assets/6206297/23570c75-0408-4dc7-8248-7cd9948b1f07)

I'm referring to something like the photo above in Spotify where it lets you share an actual photo of the album art to whatever socials you're looking for, can this be implemented?

**Comment by 25huizengek1** [comment]
I just downloaded Spotify to try this out. There is actually no difference with ViTune, but they simply added a 'stories' button for Instagram.

I won't add this though, because Instagram doesn't have support for YouTube cards.

I can add a 'share thumbnail' button or something, but that feels awkward. I'll see what I can do, but since it's technically copyright infringement I highly doubt if we should add this. Besides, taking a screenshot is as simple, right?
