### ISSUE TITLE
Exclude Specific folder(s) from local device 

### ISSUE THREAD

**Issue by srt54558** [25huizengek1/ViTune#264]
## Feature request: ...

Hello,
I really love this app and use it daily! Glad ViMusic gets continued!

As the title says, my "local" music section is full of audio recording, music, recorded calls. I would appreciate a blacklist or whitelist of folders!

**Comment by 25huizengek1** [comment]
Thank you for your appreciation!

Unfortunately, this is not possible due to the nature of Android's (new) permission system. ViTune only gets access to a list of audio files (most of the time even file proxies), and because of that I can't filter on the location of the song. This means that (unless I ask users to explicitly enable full file system access) I won't be implementing this unfortunately. Great suggestion though, it's definitely something I wanted to implement but I'm afraid I can't in a user-friendly way...

**Comment by srt54558** [comment]
> Thank you for your appreciation!
> 
> Unfortunately, this is not possible due to the nature of Android's (new) permission system. ViTune only gets access to a list of audio files (most of the time even file proxies), and because of that I can't filter on the location of the song. This means that (unless I ask users to explicitly enable full file system access) I won't be implementing this unfortunately. Great suggestion though, it's definitely something I wanted to implement but I'm afraid I can't in a user-friendly way...

Okay thanks for the information.

Making ViTune an app for playback and having full system access is okay for me too (can be an option). Thanks!
