### ISSUE TITLE
Visual indicator after trying to play an unavailable song

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#275]
Display a visual indicator when a user attempts to play a song that is unavailable due to a server-side error.
This indicator should only appear after receiving a 'song deleted' error (not in cases where the user's phone has no connection.) following an attempt to play the song, and it should disappear if the app, on a second attempt to play the song, manages to do it.

By implementing this feature, users will be notified that the specific source for a song is no longer available, prompting them to find a replacement.

![Board(1)](https://github.com/25huizengek1/ViTune/assets/108904135/24727768-c2d1-48ec-a5ac-2595fc9ae550)

**Comment by 25huizengek1** [comment]
This causes inconsistent behavior, I think, because when you have internet issues and the connection with YouTube gets timed out, the song is not unavailable but it's an issue on your part. Geolocation and internet connection also highly influence whether a song is available for you at some point in time.

You can enable Autoskip though, and turn on the notifications. I think that is a good alternative.

**Comment by Monoxide8969** [comment]
My bad, for some reason I had the notifications off and didn't see them. I agree, notifications are better for this.

I think the autoskip feature should be present as a default feature, always on and without the possibility to be turned off to avoid clutter in the settings. Maybe it's just me, but I can't think of a case where the user would want its playlist to suddently stop and to restart it manually.
