### ISSUE TITLE
Music Blend In

### ISSUE THREAD

**Issue by XelXen** [25huizengek1/ViTune#294]
## Music Blending:

I think, the app can have a music Blend in feature so before playing the next or previous song, the music fades out and the other one fades in simultaneously making it look like we never skipped off but rather transitioned into a new section of the same music.

It has been implemented in various apps before but I couldn't find it's toggle in ViTune 😅

**Comment by 25huizengek1** [comment]
Good idea. I'll see what I can do. I don't know whether cross fading is possible with consistent state, but plain fading shouldn't be a problem.

**Comment by 25huizengek1** [comment]
Due to the architecture of ExoPlayer (the player ViTune uses) / the way media works on Android in general, this is currently not possible. This has been a feature request for ExoPlayer for a long time now, and I'm afraid there is no feasible way of handling this unfortunately.

We'll have to track https://github.com/androidx/media/issues/2 for now.
