### ISSUE TITLE
Save speed/pitch for song

### ISSUE THREAD

**Issue by Monoxide8969** [25huizengek1/ViTune#307]
Add a "save for this song" button in the Speed & pitch dialog popup, to the left of the confirm button.
This remembers the setting for that single song. That's it.

A couple of side stuff from ux perspective

- How the sliders are set on the screen (the "global" speed/pitch setting) should be prioritized over the custom speed/pitch preset. (I hope I made myself clear on this one, lmk if I need to elaborate on this)

- if speed/pitch are set to 0, the "save for this song" button becomes "reset for this song"

-  if a song has a custom speed/pitch assigned to it, the little gauge indicator should appear somewhere in the player, maybe on top of the song title, or where i put the red x (just a couple ideas). Clicking on it may or may not pull up the speed/pitch menu, I don't know if it's best to leave it as an indicator or making it a button.

![Board](https://github.com/25huizengek1/ViTune/assets/108904135/0411d55d-a2c7-4bc5-b5ec-71993f792095)

I realize this is pretty niche, but I'd like to see it implemented.

**Comment by 25huizengek1** [comment]
I like the idea, I'm not sure if this makes sense, as it would complicate the menus even further. I'll put this on low prio.

**Comment by Monoxide8969** [comment]
I don't think it would complicate menus more than #261

**Comment by 25huizengek1** [comment]
I think it does, since the pitch and speed in that case would be derived as follows:

- First the app checks whether the current song has a 'saved' pitch, and if it does, it uses that one.
- Otherwise, the last **manually** specified pitch should be used
  - Changing the pitch for a song that already has a saved pitch changes the saved pitch and/or the latest manually specified pitch (I'm not even sure how to define this, should pressing the slider 'unsave' the pitch for the current song? I don't know)
- Repeat for the speed.

I think this is way too niche, given the confusion (new) users might get with this pitch menu.
