### ISSUE TITLE
Search button on Android Auto

### ISSUE THREAD

**Issue by irondave** [25huizengek1/ViTune#368]
## Feature request: 
Hi folks,
can be possible to add a search button on Android Auto UI for search music online and don't listen only the downloaded songs?
Could also use voice commands for search for road safety?

**Comment by 25huizengek1** [comment]
This already exists. ViTune supports Android Auto's play from search intent, so if your car supports a search button, you can use it. This also works using voice commands, although it may depend on your car and language what the command is (and whether it's actually available, because it unfortunately doesn't work in most languages)

I have added support for WearOS, Automotive, and Assistant in faa8b6e4a8b3888a61747336f42ed0c683d6b3d0, so I guess this can be closed.
