### ISSUE TITLE
Aspect Ratio Options

### ISSUE THREAD

**Issue by MLGHerobrine** [25huizengek1/ViTune#371]
## Feature request: Aspect Ratio Options
Referencing [closed issue 369:](https://github.com/25huizengek1/ViTune/issues/369)
I would like to see options to change the aspect ratio of thumbnails. The recent update (v1.0.6) changed thumbnails to fit the width of the screen. The issue is 1:1 thumbnails rarely fit the width of the screen, especially on a small phone like mine. The end result crops out parts of the thumbnail, making it look weird.

[As suggested by another user,](https://github.com/25huizengek1/ViTune/issues/327#issuecomment-2148813366) it would be helpful to have an adjustable option for this. Some users may want to get the most out of their screen while others may wish to see the whole thumbnail.

I appreciate the time you put into developing this and hope you will consider my suggestion.

**Comment by Monoxide8969** [comment]
I agree with @MLGHerobrine and @Enigma1309, [these changes](https://github.com/25huizengek1/ViTune/issues/369#issuecomment-2192601678) to the thumbnails introduced heavy inconsistencies depending on the phone model, and in my opinion it was definitely better as it was before.

If I'm not mistaken, this is due to [this commit](https://github.com/25huizengek1/ViTune/commit/29c8dd4d91368739fdcd61870aa063276d9024ff) (?), implemented to fix #314.

I think it would be best to revert it and, in order to address the problem of the stretched video thumbnails:
- [Have settings for them](https://github.com/25huizengek1/ViTune/issues/327#issuecomment-2148813366)
- or set it by default to crop the image with x centered and y=height of the thumbnail

Example (I'll use the same video as #314 since it's easier to demonstrate my point):
This is how it was in version 1.0.4
![104](https://github.com/25huizengek1/ViTune/assets/108904135/8e11038b-6ab9-4c09-ae99-d5af837ab9c8)

Which translates to the image being cropped this way
![104 crop](https://github.com/25huizengek1/ViTune/assets/108904135/e6f13a09-b0b7-4b52-9fcb-c85d505d306d)

This is how it is now. It doesn't look good and it's inconsistent
![106](https://github.com/25huizengek1/ViTune/assets/108904135/d7a03423-3f51-4f71-aad3-9508249d7127)

This is how it should be
![ideal](https://github.com/25huizengek1/ViTune/assets/108904135/240e58a9-bf29-4527-8bb5-66035540957d)

Which translates to the image being cropped this way
![ideal crop](https://github.com/25huizengek1/ViTune/assets/108904135/749cd9bb-192d-485a-8d57-ded9a0f8bc2f)

**Comment by 25huizengek1** [comment]
@Monoxide8969 This is not inconsistent. It tries to get the most from the available screen size on your device. This means the actual rendered thumbnail size is different for every device, screen orientation and split-screen configuration.

**Comment by Monoxide8969** [comment]
I guess that could be right, but the cropping of the videos looked broken before and looks plain weird now.

I think it would look much better if the videos' covers had the same aspect ratio ad the songs from YT Music and were just cropped properly like I showed in my previous comment.

-------- Messaggio originale --------
01/09/24 22:41, ***@***.*** [via Relay] ha scritto:

**Comment by Monoxide8969** [comment]
I guess that could be right, but the cropping of the videos looked broken before and looks plain weird now.

I think it would look much better if the videos' covers had the same aspect ratio ad the songs from YT Music and were just cropped properly like I showed in my previous comment.

**Comment by OutshineIssue** [comment]
Yeah it looks weird, there has to be some workaround so things don't get cropped.
