### ISSUE TITLE
ill pay if you can make some tweaks for me

### ISSUE THREAD

**Issue by sebsebseb9b** [25huizengek1/ViTune#385]
email me at seby9b@gmail.com if you can 

ill pay 40

**Comment by 25huizengek1** [comment]
Unfortunately I do not have a viable way of accepting donations right now, but that's ok, I work on this app for free since it's just a side project that I'm using myself daily.

Nonetheless, I'm happy to hear about your concerns about ViTune. You can impose improvements/suggestions on GitHub/in this issue ticket or hit me up at development@vitune.app

**Comment by 25huizengek1** [comment]
I edited your message since this is not a bug @sebsebseb9b

**Comment by sebsebseb9b** [comment]
hey if you have paypal i get send 40 for this. This is the music app i use
all the time

Can you get rid of all tabs except the playlist and songs tab. (and make
the playlist tabs the default) and can you hide the local tab in songs tab.

And can you get rid of the search in the songs tab please

And can you make the album art bigger.

And can you get rid of the my top in the playlist tab.

And there are 2 player modes right now and you see how the loop button is
hidden in the bottom pull up tab so can you put it there classic player
mode too.

And can you get rid of the heart button on the classic player mode.

And for the classic player mode can you make the prev and next track
buttons align with end of the scrubber .

And add a invisible button in the top left corner that you hold for 5
seconds to change between modes

can you get rid of everything with red line next to it in the menus please

when you search for something instead of saying enter a name just have it
say search
Get rid of the other versions tab when youre in a album
and can you center the playlist name under the playlist( right now its off
to the left)

and when you go into a playlist can you get rid of the enqueue and the
download button at the top leftish

**Comment by 25huizengek1** [comment]
@sebsebseb9b I responded to your email, I guess we can continue the conversation over there.

---

Unfortunately, I will not remove entire parts of the app just because of personal preference. I'll provide some feedback on your suggestions.


Also, I cannot accept donations as of right now, so please keep that in mind.


Here's the feedback:


Can you get rid of all tabs except the playlist and songs tab. (and make the playlist tabs the default) and can you hide the local tab in songs tab.


And can you get rid of the search in the songs tab please


I'm sorry, but I think there's no point in removing core functionality.


And can you make the album art bigger.


Where/in which screen should the album art be bigger?


And can you get rid of the my top in the playlist tab.


I won't remove core functionality as specified above, I'm sorry.


And there are 2 player modes right now and you see how the loop button is hidden in the bottom pull up tab so can you put it there classic player mode too.


And can you get rid of the heart button on the classic player mode.


For consistency's sake, I won't remove the like/loop button.


And for the classic player mode can you make the prev and next track buttons align with end of the scrubber .


I don't understand, please elaborate.


And add a invisible button in the top left corner that you hold for 5 seconds to change between modes


This seems counterintuitive, switching the player layout using a button in the player UI itself, let alone an invisible button, is not very useful in my opinion.


can you get rid of everything with red line next to it in the menus please


I don't understand, please explain.


when you search for something instead of saying enter a name just have it say search


I think this is just personal preference.


Get rid of the other versions tab when youre in a album


What is the point? Albums can have other versions, why shouldn't ViTune show these? There is no point in straight up removing this from the UI, just don't click on it if you don't want to see the other versions?


and can you center the playlist name under the playlist( right now its off to the left)


This is just personal preference, I think the right-aligned text belongs to ViTune/ViMusic's design. It just looks balanced in combination with the vertical side bar in my opinion.


and when you go into a playlist can you get rid of the enqueue and the download button at the top leftish


There is no point in removing this kind of functionality.



I hope you can understand my feedback. Please let me know if there are any further concerns.

**Comment by sebsebseb9b** [comment]
I could do 50 if you can
