### ISSUE TITLE
More quick actions on playing screen.

### ISSUE THREAD

**Issue by coopershaw1116** [25huizengek1/ViTune#408]
Pre Cache (Download) and Add to playlist buttons should appear somewhere on the playing now screen, perhaps on the bottom bar in-between the Loop and More Options button.

![Screenshot_20240814_231022.jpg](https://github.com/user-attachments/assets/47ca922f-c169-42fd-b32e-f4e8cc5d9b21)

**Comment by genericbetatester** [comment]
No, it shouldn't. It's literally just two clicks away. Please, the UI is still pretty neat let's not clutter it.

**Comment by cooper-shaw75** [comment]
> No, it shouldn't. It's literally just two clicks away. Please, the UI is still pretty neat let's not clutter it.

There is so much fead space that filling it wont even clutter the UI. Plus i find the More options draw that pops up when clicking the 3 dots lags because of ho many options they are so moving these would help with performance. Theres also just too many option in the Mire options pop up to where it's unfriendly to use and look at, especially if youre new to the app

**Comment by genericbetatester** [comment]
your idea is not bad in itself, I'm just concerned about the execution, I'll hate if the app's clean UI is ruined. And I agree the options in the menu is too much, it literally covers the whole screen for some songs. iirc, an issue is still open regarding that. And about making the buttons optional, I'm not sure the dev is willing to go to such lengths to add that.

**Comment by 25huizengek1** [comment]
I fully agree with @genericbetatester, so I'll have to close this issue unfortunately. I think the UI is fine as it is right now, and it can't be perfect for everyone.
