### ISSUE TITLE
Clear Queue

### ISSUE THREAD

**Issue by coopershaw1116** [25huizengek1/ViTune#428]
A button to remove all songs from the queue; cleaning it out.

**Where is this usefull?**
When you play a song from a playlist it queues the whole playlist automatically. Then when you queue a song it goes to the bottom when you may want it to play next when you dont wanna move it up the queue manually cuz theres too many songs theres because the playlist is large. A button to clear the queue as well as a button to queue a song to play next instead of at the bottom if the queue, like a "Play next" button.

**Comment by 25huizengek1** [comment]
These both already exist. Swipe down the player to close it. That way the queue is empty. (The reason this is the way to empty the queue is because otherwise the player would be an empty screen without state when the queue is empty)

When you want to play a song next, press and hold it and tap 'Play next'.
