### ISSUE TITLE
Songs automatically clear cache after 12 hours 

### ISSUE THREAD

**Issue by Kaynem706** [25huizengek1/ViTune#447]
### Steps to reproduce the bug

Download or pre cache songs and they will automatically clear cache after 12 hours

### Expected behavior

Songs should never clear cache unless i chose to clear cache

### Actual behavior

Songs automatically clear cache after 12 hours even with the song cache size at unlimited 

### Screenshots/Screen recordings

![Screenshot_20240923_143304](https://github.com/user-attachments/assets/8df646ee-3e0f-48c4-9d80-ce09067ddbce)
As you can see the cache size is at maximum

### ViTune version

1.0.9

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using Samsung galaxy ao4e running on 1ui

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
Not a bug, the app never clears cache by itself, unless the cache size exceeds the max cache size in Settings --> Cache --> Max player cache

See https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359 and https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501

**Comment by Kaynem706** [comment]
You are arrogant ,I'm telling you and showing you a screen shot and you are opposing ,your app has problems but you dont take it serious and still expect to grow ,get the f outta here

**Comment by Kaynem706** [comment]
> Not a bug, the app never clears cache by itself, unless the cache size exceeds the max cache size in Settings --> Cache --> Max player cache
> 
> See [#379 (comment)](https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359) and [#329 (comment)](https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501)



> Not a bug, the app never clears cache by itself, unless the cache size exceeds the max cache size in Settings --> Cache --> Max player cache
> 
> See [#379 (comment)](https://github.com/25huizengek1/ViTune/issues/379#issuecomment-2211387359) and [#329 (comment)](https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501)

You are arrogant ,I'm telling you and showing you a screen shot and you are opposing ,your app has problems but you dont take it serious and still expect to grow ,get the f outta here

**Comment by 25huizengek1** [comment]
<details>
  <summary>Original message by @Kaynem706</summary>

  > You are arrogant ,I'm telling you and showing you a screen shot and you are opposing ,your app has problems but you dont take it serious and still expect to grow ,get the f outta here
</details>

@Kaynem706 I understand your concerns. I also understand why you think the app is the problem here. The app never clears cache on its own whenever you haven't reached the max cache limit, as I explained earlier. Intervention by the system/IO errors/storage reliability (for example, when you put ViTune on an SD card) could degrade the stability of the cache. On both of my phones (Nothing Phone (2a) & Samsung Galaxy A12), I have had ViTune since it existed, and never lost any cache, while using ViTune daily. As I explained earlier on (#329, #379, and this issue ticket), this is not something I can fix for all Android devices, because of the many platform differences there may or may not be.

So in response to your message, yes, I take your concerns serious. ViTune is only a fork of ViMusic, and, as I admitted before, not particularly written in a style I'm familiar with and also bit messy (which is fine for a small side-project, even though I'm considering rewriting the entire app). I also do not have the time to actually turn ViTune in a large project, it just so happens that the community seems to like the app. This does not mean I **want/expect** to grow or **have** to work on this project. ViTune is a small side project, and it will stay like that, and that is fine.

I've hidden your rude message, but for the folks that want to read it, feel free to expand, not trying to hide something. In other words, I'm not trying to censor concerns by the community, but I feel like addressing it this way fits in this case.

**Comment by Wqttzicue** [comment]
> <details>
>   <summary>Original message by @Kaynem706</summary>
> 
>   > You are arrogant ,I'm telling you and showing you a screen shot and you are opposing ,your app has problems but you dont take it serious and still expect to grow ,get the f outta here
> </details>
> 
> @Kaynem706 I understand your concerns. I also understand why you think the app is the problem here. The app never clears cache on its own whenever you haven't reached the max cache limit, as I explained earlier. Intervention by the system/IO errors/storage reliability (for example, when you put ViTune on an SD card) could degrade the stability of the cache. On both of my phones (Nothing Phone (2a) & Samsung Galaxy A12), I have had ViTune since it existed, and never lost any cache, while using ViTune daily. As I explained earlier on (#329, #379, and this issue ticket), this is not something I can fix for all Android devices, because of the many platform differences there may or may not be.
> 
> So in response to your message, yes, I take your concerns serious. ViTune is only a fork of ViMusic, and, as I admitted before, not particularly written in a style I'm familiar with and also bit messy (which is fine for a small side-project, even though I'm considering rewriting the entire app). I also do not have the time to actually turn ViTune in a large project, it just so happens that the community seems to like the app. This does not mean I **want/expect** to grow or **have** to work on this project. ViTune is a small side project, and it will stay like that, and that is fine.
> 
> I've hidden your rude message, but for the folks that want to read it, feel free to expand, not trying to hide something. In other words, I'm not trying to censor concerns by the community, but I feel like addressing it this way fits in this case.

This bro made you angry...
Btw, please answer me in #460 thread 😭
