### ISSUE TITLE
An Unknown Playback Error has occured

### ISSUE THREAD

**Issue by hantu152** [25huizengek1/ViTune#467]
### Steps to reproduce the bug

after re-installed the latest one, i tried to play one song and this message appear "An Unknown Playback Error has occured"

### Expected behavior

i mean it should played perfectly with no problem

### Actual behavior

and it show a message like that

### Screenshots/Screen recordings

![Screenshot_20241012-195431](https://github.com/user-attachments/assets/e141bbb9-d97e-4a13-8e93-b5f4edc21e61)

### ViTune version

v.1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

I am using Infinix Hot 10, running on android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Driftinginfinitely** [comment]
I've been facing this issue for several days even after the update, on two devices (Android 13 and Android 14).

**Comment by 25huizengek1** [comment]
This is not something I can fix. Sometimes, YouTube returns a response (through Piped, don't worry) that states they suspect the caller is a robot. The app then retries, and gives up after a few tries. Retrying by restarting the player should do. This only happens every once in a while, and it seems YouTube is getting stricter about rate-limiting, so that should explain it. I do have plans to move off of Piped for resolving streams in the future, so that should help with the rate-limiting.

**Comment by 25huizengek1** [comment]
I've implemented a way for users to 'see for themselves' that this is the case. Go to Settings --> Other --> Show troubleshoot section --> View debug logs. Then scroll up until you see a red error message that reads something along the lines of 'playback error'. There should be a error message from YouTube Music in there.
