### ISSUE TITLE
Allow for cached data to be exported

### ISSUE THREAD

**Issue by parthbansal05** [25huizengek1/ViTune#524]
## Feature request: ...

A clear and concise description of the feature you want to request.
Have an option in settings>cache to export the cache music to a folder on the device in MP3 or other audio formats

**Comment by Wqttzicue** [comment]
Uhh, if cache is saved as mp3 format, why not tho

**Comment by MLGHerobrine** [comment]
Not sure if cache is saved as mp3, but if so this would be great.

Alternative for now: download NewPipe, use the "Open In YouTube" button in ViTune, and download audio from NewPipe.

Looking forward to if this feature gets added, mainly for mass saving.

**Comment by Mirko117** [comment]
I think that adding that feature would violate Youtube's copyright laws.

**Comment by 25huizengek1** [comment]
As discussed earlier, I won't add something that turns the music into mp3 files.

@Wqttzicue It is not, ViTune stores chunked audio data that it received directly from YouTube (sometimes varies in file format)
@Mirko117 That is correct, or rather, it would violate (almost) all international copyright laws (YouTube doesn't make the law). Although I'm not a lawyer, I believe letting users listen to the music is not really a(n) (big) issue, but exporting it is just not something I want to deal with. I suggest installing apps specialized in downloading music from YouTube, like YTDLnis. It is possible to do this from ViTune (altough I don't see the advantage, since all music in ViTune gets cached and made available for offline use anyway), in the song menu, hit the share icon and share with your YouTube downloader of choice.
