### ISSUE TITLE
Make Vitune available through the google assistant

### ISSUE THREAD

**Issue by sidsharths1245** [25huizengek1/ViTune#537]
As of now the Google assistant only recognises YouTube music and Spotify as music applications on my phone. Is there a way for it to recognise Vitune as well?

**Comment by sidsharths1245** [comment]
Hmm it does work with other third party music apps.

What I'm suggesting is the functionality as in, when I say, "hey google, play this song". instead of saying you don't have have a music app it plays the song in ViTune.

**Comment by Wqttzicue** [comment]
> Hmm it does work with other third party music apps.
> 
> What I'm suggesting is the functionality as in, when I say, "hey google, play this song". instead of saying you don't have have a music app it plays the song in ViTune.

K, m
I may be wrong, but i have no idea how you integrared some other third party music app like ViTune in Google Assistant

**Comment by 25huizengek1** [comment]
ViTune actually already has support for Google Assistant (and it actually works in cars!). Unfortunately, when you ask Google Assistant to play through ViTune, it searches for ViTune on the Play Store. And since ViTune is actually not on the Play Store, I guess this will never work. Unless of course Epic v. Google opens up new doors 👀
