### ISSUE TITLE
My sounds so sloww

### ISSUE THREAD

**Issue by Shark-SVG** [25huizengek1/ViTune#579]
### Steps to reproduce the bug

Why my volume sounds very2 slowww 

https://github.com/user-attachments/assets/c5939e72-700b-4e08-85fc-9e559eacc3f8

### Expected behavior

The volume sound very slow i can hear it but very slow 

### Actual behavior

https://github.com/user-attachments/assets/24389db8-c729-46d1-b716-e1f899211759

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/834deb30-0f0f-4cca-96c6-4b1c1ff1158a

### Logs

https://github.com/user-attachments/assets/393d97fb-e3f7-48cc-ab71-8468e3031610

### ViTune version

V.1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Realme 12 pro plus

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment]
In your screen recording, the volume setting of your device never gets accounted for, so I don't see any problems with the playback according to the screen recording.

If I understood you correctly, adjusting the device volume gets delayed. However, this has nothing to do with ViTune. Contact your device's manufacturer about this. If your device is running slow, it may not catch up to your inputs in time, so that may cause some issues you are experiencing. If you want to ensure ViTune is causing some kind performance issues causing input delay, turn down the quality of the seek bar, or even disable it, or close ViTune altogether but keep the player running.
